version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/pruebaAWS/
hooks:
  BeforeInstall:
    - location: script/BeforeInstall.sh
      timeout: 90
      runas: ec2-user
  AfterInstall:
    - location: script/AfterInstall.sh
      timeout: 90
      runas: ec2-user
  ApplicationStart:
    - location: script/ApplicationStart.sh
      timeout: 90
      runas: ec2-user